### ISSUE TITLE
เลือกหัวข้อเกม

### ISSUE THREAD

**Issue by Wayu650610806** [Wayu650610806/Scratch-Game-Group-28#1]
แนะนำให้สร้างเกม โดยคิดเกมที่สมาชิกทีมชอบเล่น และพิจารณาความยากง่ายให้เหมาะสม หากสนใจทำโครงงานอื่นที่ไม่ใช้เกมก็ขอให้แน่ใจว่ามีความน่าสนใจและความซับซ้อนเหมาะสม

Theme - ถ้าเป็นไปได้ให้สร้าง Theme ของเกมที่เชื่อมโยงกับเหตุการณ์ในปัจจุบัน ไม่ว่าจะเป็นในชีวิตของสมาชิกคนใดคนหนึ่ง (เช่น ประสบการณ์การเรียนในมหาวิทยาลัย อยู่หอพัก ฯลฯ) หรือเหตุการณ์ของสังคมปัจจุบัน (เช่น COVID-19, น้ำท่วม, ข่าว, trend ต่าง ๆ, ดารา, ฯลฯ) การกำหนด Theme มักช่วยทำให้โครงงานมีความน่าสนใจมากขึ้น

เตรียมนำเสนอ - ให้นำเสนอโดยสร้างเป็น slide ตาม Template ที่กำหนดให้ คือ ประกอบด้วย
ภาพร่างของโครงงานเมื่อทำเสร็จแล้ว - แสดงให้เห็นว่าเกมหน้าตาเป็นอย่างไร เล่นอย่างไร
การแบ่งงานของทีม - ใครทำหน้าที่อะไรบ้าง

การวางแผนการทำงาน - แสดงการวางแผนโดยใช้ Git hub issues สร้าง Milestone กับ issue ที่เหมาะสม ตลอดจนกำหนดผู้รับผิดชอบแต่ละงาน

**Comment by Fittokung** [comment]
อยากทำเกมแนว action ไม่ก็ puzzle

**Comment by Wayu650610806** [comment]
อยากทำเกมผี XD

**Comment by Pongpor** [comment]
puzzle คือเกมตัวต่อหรอ?

**Comment by Fittokung** [comment]
เกมแก้ปริศนาอะ พวก Sudoku, Jigsaw, 2048

**Comment by Pongpor** [comment]
น่าส่นใจแต่เกมผีก็น่าสน!!

**Comment by Wayu650610806** [comment]
งั้นหัวข้อเป็น เกมผีละกัน!
